### ISSUE TITLE
Use High resolution time for calculating time taken during openmp

### ISSUE THREAD

**Issue by aniketdhole07** [Keylost/BilinearImageResize#1]
When I used the `clock_t` to calculate time when using openmp it gives wrong results <br>

Use :
    
    auto start = chrono::high_resolution_clock::now();
	for (int i = 0; i < RESIZE_CALLS_NUM; i++)
	{
		delete[] argb_res_cpu;
		argb_res_cpu = resizeBilinear_cpu(argb, image.cols, image.rows, newSz.width, newSz.height);
	}
	auto end = chrono::high_resolution_clock::now();
    double time_taken =  chrono::duration_cast<chrono::nanoseconds>(end - start).count(); 
    time_taken *= 1e-9; 
	printf("Time CPU: %f\n", time_taken);

**Comment by Keylost** [comment]
This app targets windows. clock() should work fine with windows, coz it returns wall-clock time. On POSIX systems it returns cpu time and result would be wrong for MT apps. What platform and compiler are u using?
P.S. U're right, it's better to use chrono) It's platform-independent
